# Generated by Django 2.2.5 on 2019-10-01 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191001_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_done',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
