# Generated by Django 2.2.5 on 2019-10-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191001_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_type',
        ),
    ]
