# Generated by Django 2.2.5 on 2019-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191002_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sm_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dinner_Platters',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Regular_Pizza',
        ),
        migrations.DeleteModel(
            name='Salads',
        ),
        migrations.DeleteModel(
            name='Sicilian_Pizza',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
