# Generated by Django 2.2.5 on 2019-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191004_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='price',
            new_name='lg_price',
        ),
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='price',
            new_name='lg_price',
        ),
        migrations.RenameField(
            model_name='sicilian_pizza',
            old_name='price',
            new_name='lg_price',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='price',
            new_name='lg_price',
        ),
        migrations.RemoveField(
            model_name='dinner_platter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='regular_pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AddField(
            model_name='dinner_platter',
            name='sm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='sm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='sm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='sm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
