# Generated by Django 2.2.5 on 2019-10-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
    ]
