# Generated by Django 2.2.5 on 2019-10-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191011_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular_pizza',
            name='extras',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
