# Generated by Django 2.2.5 on 2019-10-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_regular_pizza_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicilian_pizza',
            name='extras',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
