# Generated by Django 2.2.5 on 2019-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_sicilian_pizza_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('flavor', models.CharField(max_length=20)),
                ('extra_num', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('extra_desc', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='title',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
