# Generated by Django 2.2.5 on 2019-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20191012_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='extra_desc',
            field=models.CharField(max_length=20),
        ),
    ]
