# Generated by Django 2.2.5 on 2019-10-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191014_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_rec',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_done',
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(to='orders.Cart'),
        ),
    ]
