# Generated by Django 2.2.5 on 2019-10-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20191016_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='orders.food_item'),
        ),
    ]
