# Generated by Django 2.2.5 on 2019-10-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20191017_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='orders.Food_item'),
        ),
    ]
