# Generated by Django 2.2.5 on 2019-10-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20191017_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='food_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
