# Generated by Django 2.2.5 on 2019-10-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_cart_food_item_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food',
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='orders.Food_item'),
        ),
    ]
